environment:
  matrix:
  - platform: x64
    MINGW_ARCH: x86_64
    MINGW_ROOT: C:\msys64\mingw64
    MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  - platform: x86
    MSYSTEM: MINGW32
    MINGW_ROOT: C:\msys64\mingw32
    MINGW_ARCH: x86
    PATH: C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%

build_script:
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && autoreconf"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && ./configure"
  - bash -lc "exec 0</dev/null && cd $APPVEYOR_BUILD_FOLDER && make"
  - bash -lc true

artifacts:
  - path: src\iedera.exe
    name: Releases

deploy:
  provider: GitHub
  description: 'Mac OS X and Windows 64 binaries'
  release: ${APPVEYOR_REPO_TAG_NAME}
  auth_token:
    secure: tHdOZd4WuISqvOGoP2UQQMH98teawtdSIZikUbanK4/06NzgINRT6LspbH1pdme3
  artifact: /iedera.exe/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
    platform: x64
